# Generated by Django 5.1.3 on 2024-11-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("painting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="painting",
            name="gallery",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paintings",
                to="gallery.gallery",
            ),
        ),
    ]
