# Generated by Django 5.1.3 on 2024-11-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_image_url_gallery_cover_painting'),
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='gallery.gallery'),
        ),
    ]
