# Generated by Django 5.1.3 on 2024-11-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_painting_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='artist',
        ),
    ]
