# Generated by Django 5.1.3 on 2025-01-25 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0004_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saved',
            unique_together={('user', 'painting')},
        ),
    ]
