# Generated by Django 5.1.3 on 2025-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
