# Generated by Django 5.1.3 on 2024-11-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_painting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries_as_cover', to='painting.painting'),
        ),
    ]
