# Generated by Django 5.1.3 on 2024-11-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
