# Generated by Django 5.1.3 on 2025-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_customuser_cover_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
