# Generated by Django 5.1.3 on 2024-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_customuser_cover_painting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_path',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
