# Generated by Django 5.1.3 on 2024-11-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_customuser_cover_painting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
