# Generated by Django 5.1.3 on 2024-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_customuser_is_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
