# Generated by Django 5.1.3 on 2024-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
