# Generated by Django 5.1.3 on 2024-12-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0003_customuser_dark_light_theme_customuser_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Dark_light_theme',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Theme',
        ),
    ]
