# Generated by Django 5.1.3 on 2024-11-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0003_remove_customuser_profile_picture_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_artists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_paintings',
            field=models.IntegerField(default=0),
        ),
    ]
