# Generated by Django 5.1.3 on 2024-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0004_remove_customuser_dark_light_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Dark_light_theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
