# Generated by Django 5.1.3 on 2024-11-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registering", "0005_customuser_date_of_birth_customuser_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="region",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="national_id",
            new_name="nationality",
        ),
        migrations.AddField(
            model_name="customuser",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_painter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_painting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_painting_style",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_painting_technique",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_painting_to_own",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
