<<<<<<< Updated upstream
# Generated by Django 5.1.3 on 2024-12-10 17:38

import django.db.models.deletion
import django_countries.fields
=======
# Generated by Django 5.1.3 on 2024-12-14 05:49

import django.db.models.deletion
from django.conf import settings
>>>>>>> Stashed changes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='utils.country')),
=======
                ('country', models.CharField(default='Iran', max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('iso3_code', models.CharField(default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Iran', max_length=100)),
                ('city', models.CharField(default='Tehran', max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> Stashed changes
            ],
        ),
    ]
