# Generated by Django 5.1.4 on 2024-12-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(db_index=True, default="Iran", max_length=100),
                ),
                ("name", models.CharField(db_index=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
