# Generated by Django 5.1.3 on 2024-12-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='iso3_code',
        ),
    ]
